### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.utils.serialization'

### ISSUE THREAD

**Issue by singhkavinder** [KarelZhang/CSDNet-CSDGAN#2]
I am using pytorch version 0.4.1 and torchvision 0.2.0 on my device with cuda 9.2.

I ran code to generate results and it was working fine previously. Now, suddenly it is showing error: ModuleNotFoundError: No module named 'torch.utils.serialization'.
 
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    from models.test_model import TestModel
  File "/home/ppp/Desktop/PYTORCH-LOW-LIGHT/CSDNet-CSDGAN-master/models/test_model.py", line 8, in <module>
    from . import networks as networks
  File "/home/ppp/Desktop/PYTORCH-LOW-LIGHT/CSDNet-CSDGAN-master/models/networks.py", line 10, in <module>
    from torch.utils.serialization import load_lua
ModuleNotFoundError: No module named 'torch.utils.serialization'

**Comment by yaz94** [comment]
Hi @singhkavinder,

Install torch==0.4.1, since this command has been removed in the newest torch versions >=1.1.0.

Hope it works,
Cheers,

**Comment by 9bxlue** [comment]
you can refer https://blog.csdn.net/weixin_54186372/article/details/115391432 to fit your code
